variable "vpc" {}
variable "env" {}
variable "tags" {}
variable "default_vpc_cidr" {}
variable "default_vpc_id" {}
variable "account_id" {}
variable "default_route_table_id" {}
variable "route53_zone_id" {}
variable "bastion_cidrs" {}
variable "prometheus_cidrs" {}